#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/ShulamitP_Mizrahi_Calc_Api/ && \
    dotnet build src/ShulamitP_Mizrahi_Calc_Api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/ShulamitP_Mizrahi_Calc_Api/ShulamitP_Mizrahi_Calc_Api.csproj --launch-profile web"
