/*
 * Mizrahi Arithmetic API
 *
 * EST API that performs basic arithmetic operations. Implemented by Shulamit Petranker for Matrix/BM assignment.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using ShulamitP_Mizrahi_Calc_Api.Attributes;
using ShulamitP_Mizrahi_Calc_Api.Security;
using Microsoft.AspNetCore.Authorization;
using ShulamitP_Mizrahi_Calc_Api.Models;
using System.Threading.Tasks;
using ShulamitP_Mizrahi_Calc_Api.Handlers.Authentication;

namespace ShulamitP_Mizrahi_Calc_Api.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AuthenticationController : ControllerBase
    {
        private readonly ILoginHandler _loginHandler;

        public AuthenticationController(ILoginHandler loginHandler) 
        { 
            _loginHandler = loginHandler;
        }
        /// <summary>
        /// Authenticate user and generate JWT token
        /// </summary>
        /// <remarks>Accepts credentials and returns a JWT token if valid.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Authentication successful</response>
        /// <response code="401">Authentication failed - invalid credentials</response>
        [HttpGet]
        [Route("/test-436/ShulamitP-Mizrahi-Calc-Api/1.0.0/api/auth/login")]
        [ValidateModelState]
        [SwaggerOperation("Login")]
        [SwaggerResponse(statusCode: 200, type: typeof(LoginResponse), description: "Authentication successful")]
        public virtual async Task<IActionResult> Login()
        {
            // קריאה להנדלר  
            var response = _loginHandler.GetJwt();

            // אם קריאת ההנדלר מחזירה null ? אימות נכשל
            if (response == null)
            {
                return Unauthorized("Invalid credentials.");
            }

            return Ok(response);
        }
    }
}
